name: Update Confluence Pages

on:
  push:
    branches:
      - main  # Adjust this as needed

jobs:
  update-confluence:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the main repository (this repository)
      - name: Checkout Main Repository
        uses: actions/checkout@v4

      # Step 2: Clone the source repository into a specific directory
      - name: Clone Source Repository
        env:
          SOURCE_REPO_TOKEN: ${{ secrets.SOURCE_REPO_TOKEN }}
        run: |
          git clone https://x-access-token:${SOURCE_REPO_TOKEN}@github.com/owner/source-repo.git source-repo
          cd source-repo
          echo "Cloned source repository into 'source-repo' directory."

      # Step 3: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use the Node.js version compatible with your script

      # Step 4: Install Dependencies
      - name: Install Dependencies
        working-directory: ./source-repo
        run: npm install

      # Step 5: Run the Script
      - name: Run Main Script
        env:
          CONFLUENCE_PAT: ${{ secrets.CONFLUENCE_PAT }}
        working-directory: ./source-repo
        run: node main.js $CONFLUENCE_PAT ./ 